spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/honeypot}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:honeypot}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:honeypot}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=false
spring.jpa.hibernate.ddl-auto=update
